### ISSUE TITLE
Issue in search 

### ISSUE THREAD

**Issue by sujitrp** [Gifford47/OH_find_objects#1]
Facing error in search @ pretty table "ImportError: No module named prettytable"

Tried installing prettytable but did not working 

```
openhabian@PI100:~ $ pip install https://pypi.python.org/packages/source/P/PrettyTable/prettytable-0.7.2.tar.bz2
-bash: pip: command not found
openhabian@PI100:~ $ pip3 install https://pypi.python.org/packages/source/P/PrettyTable/prettytable-0.7.2.tar.bz2
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://pypi.python.org/packages/source/P/PrettyTable/prettytable-0.7.2.tar.bz2
  Downloading https://pypi.python.org/packages/source/P/PrettyTable/prettytable-0.7.2.tar.bz2
Building wheels for collected packages: prettytable
  Running setup.py bdist_wheel for prettytable ... done
  Stored in directory: /home/openhabian/.cache/pip/wheels/29/73/c9/3e063a66859af18585f8e1439f92dcc27b8c13ae400bb8c89e
Successfully built prettytable
Installing collected packages: prettytable
Successfully installed prettytable-0.7.2
openhabian@PI100:~ $ ./find_oh_objects.py light
-bash: ./find_oh_objects.py: No such file or directory
openhabian@PI100:~ $ cd /etc/openhab/scripts
openhabian@PI100:/etc/openhab/scripts $ ./find_oh_objects.py light
Traceback (most recent call last):
  File "./find_oh_objects.py", line 8, in <module>
    from prettytable import PrettyTable
ImportError: No module named prettytable
openhabian@PI100:/etc/openhab/scripts $ pip install PrettyTable
-bash: pip: command not found
openhabian@PI100:/etc/openhab/scripts $ pip3 install PrettyTable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: PrettyTable in /home/openhabian/.local/lib/python3.7/site-packages (0.7.2)
openhabian@PI100:/etc/openhab/scripts $ python -m pip install --upgrade pip
/usr/bin/python: No module named pip
openhabian@PI100:/etc/openhab/scripts $ python -m pip3 install --upgrade pip3
/usr/bin/python: No module named pip3
openhabian@PI100:/etc/openhab/scripts $ python -m pip3 install --upgrade pip
/usr/bin/python: No module named pip3
openhabian@PI100:/etc/openhab/scripts $ ./find_oh_objects.py light
Traceback (most recent call last):
  File "./find_oh_objects.py", line 8, in <module>
    from prettytable import PrettyTable
ImportError: No module named prettytable
openhabian@PI100:/etc/openhab/scripts $
```

**Comment by Gifford47** [comment]
make sure you are running python 3 and you have installed prettytable for python3

**Comment by sujitrp** [comment]
Hi I am getting following error

openhabian@PI100:/etc/openhab/scripts $ python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> ./find_oh_objects.py
  File "<stdin>", line 1
    ./find_oh_objects.py
    ^
SyntaxError: invalid syntax
>>>

**Comment by sujitrp** [comment]
openhabian@PI100:/etc/openhab/scripts $ python3 find_oh_objects.py light

![image](https://user-images.githubusercontent.com/7476632/116968969-1e381180-acd3-11eb-8997-08fa892b4015.png)
